# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
name: $(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd).$(BuildCounter)

trigger:
  - main
  - release/*

pool: $(WindowPool)

variables:
  - name: BuildConfiguration
    value: "release"
  - name: BuildPlatform
    value: "any cpu"
  - name: BuildCounter
    value: $[counter(format('{0:yyyyMMdd}', pipeline.startTime), 1)]
  - name: UKHOAssemblyCompany
    value: "UK Hydrographic Office"
  - name: UKHOAssemblyVersionPrefix
    value: "1.0."
  - name: UKHOAssemblyProduct
    value: "File Share Desktop Client"
  - name: WindowPool
    value: "NautilusBuild"
  - name: coverityPool
    value: NautilusBuild
  - group: Covscan-vars

resources:
  repositories:
    - repository: covscan
      type: github
      name: UKHO/coverityscan-buildtemplates
      endpoint: UKHO
      ref: refs/heads/master

stages:
  - stage: CoverityScan
    displayName: "Coverity Scan"
    pool:
      name: $(coverityPool)
    jobs:
    - job: Coverity
      workspace:
        clean: all
      steps:
        - checkout: self
          submodules: recursive
        - task: UseDotNet@2
          displayName: 'Use .NET Core sdk'
          inputs:
            packageType: sdk
            version: 6.0.x
            installationPath: $(Agent.ToolsDirectory)/dotnet
        - checkout: covscan
        - template: dotnet-cov.yml@covScan
          parameters:
            CovHostUrl: "$(CovHostUrl)"
            CovUser: "$(CovUser)"
            CovPwd: "$(CovPwd)"
            StreamName: "file-share-service-desktop-client"
            BuildCommand: "$(Build.Repository.LocalPath)/file-share-service-desktop-client/file-share-service-desktop-client/FileShareService.DesktopClient.csproj"
            StripPath: $(Build.Repository.LocalPath)/file-share-service-desktop-client
            CoverityScanPath: $(Build.Repository.LocalPath)/coverityscan-buildtemplates

  - stage: PERFORM_DEPENDENCYCHECK_DOTNETBUILD_DOTNETTEST_AND_PUBLISH
    displayName: "Build (inc DependencyChecker, Dotnet Build , dotnet test and publish artifact )"
    dependsOn: []
    jobs:
      - job:
        workspace:
          clean: all # what to clean up before the job runs outputs | resources | all
        displayName: "DependencyChecker"

        steps:
          - task: UseDotNet@2
            displayName: 'Use .NET Core sdk'
            inputs:
              packageType: sdk
              useGlobalJson: true

          - task: CmdLine@1
            displayName: "Run OWASP Dependency Checker"
            inputs:
              filename: 'dependency-check.bat'
              arguments: '--project "File-Share-Service-Desktop-Client - $(Build.SourceBranchName)" --scan "$(Build.SourcesDirectory)" --out "$(Build.SourcesDirectory)\DCReport" --suppression $(Build.SourcesDirectory)\NVDSuppressions.xml --noupdate'

          - task: PublishBuildArtifacts@1
            displayName: "Publish Artifact: OWASP Dependency Checker Report"
            inputs:
              PathtoPublish: '$(Build.SourcesDirectory)\DCReport'
              ArtifactName: "OWASP Dependency Checker Report"

          - task: PowerShell@1
            displayName: "Fail Build if Dependency Check Finds Any Vulnerabilities"
            inputs:
              scriptType: inlineScript
              arguments: '-ReportLocation $(Build.SourcesDirectory)\DCReport\*'
              inlineScript: |
                param($ReportLocation)
                Invoke-VulnerabilityCheck -ReportLocation $ReportLocation

      - job: BuildAndTest
        workspace:
          clean: all
        displayName: "Dotnet Build test publish"
        steps:
          - task: PowerShell@2
            displayName: "Output Environment Variables"
            inputs:
              targetType: inline
              script: |
                gci env:
                $CurrentYear = Get-Date -Format "yyyy"
                $AssemblyCopyright = "Copyright © UK Hydrographic  Office $CurrentYear"
                echo "##vso[task.setvariable variable=UKHOAssemblyCopyright]${AssemblyCopyright}"

          - task: PowerShell@2
            displayName: "Set assembly version numbers based on build ID"
            inputs:
              targetType: filePath
              filePath: '$(Build.SourcesDirectory)\Apply-AssemblyVersionAndDefaults.ps1'
              arguments: >
                -buildNumber "$(Build.BuildNumber)" 
                -solutionDirectory "$(Build.SourcesDirectory)\" 
                -UKHOAssemblyCompany "$env:UKHOAssemblyCompany" 
                -UKHOAssemblyCopyright "$env:UKHOAssemblyCopyright" 
                -UKHOAssemblyVersionPrefix "$env:UKHOAssemblyVersionPrefix" 
                -UKHOAssemblyProduct "$env:UKHOAssemblyProduct"
                -SourceRevisionId "$(Build.SourceVersion)" 

          - task: UseDotNet@2
            displayName: 'Use .NET Core sdk'
            inputs:
              packageType: sdk
              useGlobalJson: true

          - task: NuGetToolInstaller@1
            inputs:
              versionSpec: 
            
          - task: DotNetCoreCLI@2
            displayName: ".Net Core - NuGet restore"
            inputs:
              command: restore
              projects: |
                **/*.csproj
                !**/*Tests.csproj
              feedsToUse: config
              noCache: true
              nugetConfigPath: '$(Build.SourcesDirectory)\BuildNuget.config'
              workingDirectory: '$(Build.SourcesDirectory)'
    
          - task: DotNetCoreCLI@2
            displayName: "dotnet build"
            inputs:
              command: "build"
              projects: "**/*.csproj"
              arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'

          - task: DotNetCoreCLI@2
            displayName: "dotnet test"
            inputs:
              command: "test"
              projects: "**/*Tests.csproj"
              arguments: '--configuration $(BuildConfiguration) --collect "Code coverage"'
              
          - task: PublishTestResults@2
            inputs:
              testRunner: VSTest
              testResultsFiles: '**/*.trx'

          - task: DotNetCoreCLI@2
            displayName: Publish Project
            inputs:
              command: publish
              projects: |
                **/FileShareService.DesktopClient.csproj
              publishWebProjects: false
              zipAfterPublish: false
              arguments:  '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)/publish /p:PublishSingleFile=true -r win-x64 '

          - task: PublishPipelineArtifact@1
            displayName: Publish Pipeline Atrifact
            inputs:
              path: $(Build.ArtifactStagingDirectory)/publish
              artifact: $(Build.DefinitionName)

      - job:
        displayName: "Build Installer"
        dependsOn:
        - BuildAndTest
        steps:
          - task: UseDotNet@2
            displayName: 'Use .NET Core sdk'
            inputs:
              packageType: sdk
              useGlobalJson: true

          - task: DotNetCoreCLI@2
            displayName: Publish Project
            inputs:
              command: publish
              projects: |
                **/FileShareService.DesktopClient.csproj
              publishWebProjects: false
              zipAfterPublish: false
              arguments:  '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)/publish /p:PublishSingleFile=true -r win-x64 '

          - task: VSBuild@1
            displayName: 'Build the Installer'
            inputs:
              solution: file-share-service-desktop-client.sln
              msbuildArgs: '/p:FSSPublishDir=$(Build.ArtifactStagingDirectory)/publish/file-share-service-desktop-client'
              platform: '$(BuildPlatform)'
              configuration: '$(BuildConfiguration)_Installer'

          - task: PublishPipelineArtifact@1
            displayName: Publish Installer
            inputs:
              path: $(Build.SourcesDirectory)/Installer/FileShareService.DesktopClient.Installer/bin/$(BuildConfiguration)
              artifact: $(Build.DefinitionName)_installer