# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
name: $(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd).$(BuildCounter)

parameters:
  - name: SnykOnlyFailIfFixable
    displayName: "Snyk - fail only if an issue has an available fix"
    type: boolean
    default: false
  - name: SnykPassOnIssues
    displayName: "Snyk - don't fail if issues found"
    type: boolean
    default: false

trigger:
  - main
  - release/*

pool: $(WindowsPool1)

variables:
  - name: BuildConfiguration
    value: "release"
  - name: BuildPlatform
    value: "any cpu"
  - name: BuildCounter
    value: $[counter(format('{0:yyyyMMdd}', pipeline.startTime), 1)]
  - name: UKHOAssemblyCompany
    value: "UK Hydrographic Office"
  - name: UKHOAssemblyVersionPrefix
    value: "1.0."
  - name: UKHOAssemblyProduct
    value: "File Share Desktop Client"
  - name: WindowsPool1
    value: "NautilusBuild"
  - name: WindowsPool2
    value: "Mare Nubium"
  - name: coverityPool
    value: NautilusBuild
  - name: snykAbzuOrganizationId
    value: aeb7543b-8394-457c-8334-a31493d8910d

stages:
  - stage: VulnerabilityChecks
    displayName: Vulnerability checks
    dependsOn: []
    jobs:
      - job: Snyk
        displayName: Run Snyk security scans
        pool: $(WindowsPool2)
        steps:
          - task: UseDotNet@2
            displayName: 'Use .NET Core sdk'
            inputs:
              packageType: sdk
              useGlobalJson: true

          - task: DotNetCoreCLI@2
            displayName: .NET - NuGet restore
            inputs:
              command: restore
              projects: |
                **/*.csproj
              feedsToUse: config
              noCache: true
              nugetConfigPath: '$(Build.SourcesDirectory)\BuildNuget.config'
              workingDirectory: '$(Build.SourcesDirectory)'

          - task: UkhoSnykScanTask@0
            displayName: Snyk SAST scan
            condition: succeededOrFailed()
            inputs:
              failOnIssues: ${{ not(parameters.SnykPassOnIssues) }}
              failOnThreshold: high
              organization: $(snykAbzuOrganizationId)
              serviceConnectionEndpoint: Snyk
              codeSeverityThreshold: low
              testType: code
              monitorwhen: never
              ${{ if eq(parameters.SnykOnlyFailIfFixable, true) }}:
                additionalArguments: --fail-on=all

          - task: UkhoSnykScanTask@0
            displayName: Snyk SCA scan
            condition: succeededOrFailed()
            inputs:
              failOnIssues: ${{ not(parameters.SnykPassOnIssues) }}
              failOnThreshold: high
              organization: $(snykAbzuOrganizationId)
              serviceConnectionEndpoint: Snyk
              codeSeverityThreshold: low
              testType: app
              monitorwhen: never
              severityThreshold: low
              ${{ if eq(parameters.SnykOnlyFailIfFixable, true) }}:
                additionalArguments: --all-projects --fail-on=all
              ${{ else }}:
                additionalArguments: --all-projects

  - stage: BuildTestPublish
    displayName: "Build, test and publish"
    dependsOn: []
    jobs:
      - job: BuildAndTest
        workspace:
          clean: all
        displayName: "Dotnet Build test publish"
        steps:
          - template: ./Update-AssemblyProperties.yaml  
            parameters:
              buildNumber: $(Build.BuildNumber)
              solutionDirectory: $(Build.SourcesDirectory)
              UKHOAssemblyCompany: $(UKHOAssemblyCompany)
              UKHOAssemblyCopyright: $(UKHOAssemblyCopyright)
              UKHOAssemblyVersionPrefix: $(UKHOAssemblyVersionPrefix)
              UKHOAssemblyProduct: $(UKHOAssemblyProduct)
              SourceRevisionId: $(Build.SourceVersion)

          - task: UseDotNet@2
            displayName: 'Use .NET Core sdk'
            inputs:
              packageType: sdk
              useGlobalJson: true

          - task: NuGetToolInstaller@1
            inputs:
              versionSpec: 
            
          - task: DotNetCoreCLI@2
            displayName: ".Net Core - NuGet restore"
            inputs:
              command: restore
              projects: |
                **/*.csproj
                !**/*Tests.csproj
              feedsToUse: config
              noCache: true
              nugetConfigPath: '$(Build.SourcesDirectory)\BuildNuget.config'
              workingDirectory: '$(Build.SourcesDirectory)'
    
          - task: DotNetCoreCLI@2
            displayName: "dotnet build"
            inputs:
              command: "build"
              projects: "**/*.csproj"
              arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'

          - task: DotNetCoreCLI@2
            displayName: "dotnet test"
            inputs:
              command: "test"
              projects: "**/*Tests.csproj"
              arguments: '--configuration $(BuildConfiguration) --collect "Code coverage"'
              
          - task: PublishTestResults@2
            inputs:
              testRunner: VSTest
              testResultsFiles: '**/*.trx'

          - task: DotNetCoreCLI@2
            displayName: Publish Project
            inputs:
              command: publish
              projects: |
                **/FileShareService.DesktopClient.csproj
              publishWebProjects: false
              zipAfterPublish: false
              arguments:  '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)/publish /p:PublishSingleFile=true -r win-x64 '

          - task: PublishPipelineArtifact@1
            displayName: Publish Pipeline Atrifact
            inputs:
              path: $(Build.ArtifactStagingDirectory)/publish
              artifact: $(Build.DefinitionName)

      - job:
        displayName: "Build Installer"
        dependsOn:
        - BuildAndTest
        pool: 
          name: $(WindowsPool1)
          demands:
          - WIX
        steps:
          - template: ./Update-AssemblyProperties.yaml  
            parameters:
              buildNumber: $(Build.BuildNumber)
              solutionDirectory: $(Build.SourcesDirectory)
              UKHOAssemblyCompany: $(UKHOAssemblyCompany)
              UKHOAssemblyCopyright: $(UKHOAssemblyCopyright)
              UKHOAssemblyVersionPrefix: $(UKHOAssemblyVersionPrefix)
              UKHOAssemblyProduct: $(UKHOAssemblyProduct)
              SourceRevisionId: $(Build.SourceVersion)

          - task: UseDotNet@2
            displayName: 'Use .NET Core sdk'
            inputs:
              packageType: sdk
              useGlobalJson: true

          - task: DotNetCoreCLI@2
            displayName: Publish Project
            inputs:
              command: publish
              projects: |
                **/FileShareService.DesktopClient.csproj
              publishWebProjects: false
              zipAfterPublish: false
              arguments:  '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)/publish /p:PublishSingleFile=true -r win-x64 '

          - task: VSBuild@1
            displayName: 'Build the Installer'
            inputs:
              solution: file-share-service-desktop-client.sln
              msbuildArgs: '/p:FSSPublishDir=$(Build.ArtifactStagingDirectory)/publish/file-share-service-desktop-client'
              platform: '$(BuildPlatform)'
              configuration: '$(BuildConfiguration)_Installer'

          - task: PublishPipelineArtifact@1
            displayName: Publish Installer
            inputs:
              path: $(Build.SourcesDirectory)/Installer/FileShareService.DesktopClient.Installer/bin/$(BuildConfiguration)
              artifact: $(Build.DefinitionName)_installer